/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: JessSwynn (https://sketchfab.com/JessSwynn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/happy-halloween-f969f211d8914c12a56cdb4c08829920
Title: Happy Halloween
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="63cd3751837a4246b5a6c7c92e353016fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="EvilEyes" position={[0.24, 0.89, 0.82]} rotation={[-1.52, 0.05, -0.06]} scale={0.87}>
                  <mesh name="EvilEyes_ScaryEyes_0" geometry={nodes.EvilEyes_ScaryEyes_0.geometry} material={materials.ScaryEyes} />
                </group>
                <group name="Base" position={[0, -0.24, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Base_Ground_0" geometry={nodes.Base_Ground_0.geometry} material={materials.Ground} />
                </group>
                <group name="Bat" position={[3.8, 4.07, 3.32]} rotation={[-1.55, -0.51, 2.97]} scale={2.79}>
                  <mesh name="Bat_CatandBats_0" geometry={nodes.Bat_CatandBats_0.geometry} material={materials.CatandBats} />
                </group>
                <group name="Bat001" position={[3.12, 4.82, 3.26]} rotation={[-1.32, -0.49, -2.96]} scale={2.27}>
                  <mesh name="Bat001_CatandBats_0" geometry={nodes.Bat001_CatandBats_0.geometry} material={materials.CatandBats} />
                </group>
                <group name="Bat2" position={[2.56, 5, 2.3]} rotation={[-1.82, -1, 2.98]} scale={2.16}>
                  <mesh name="Bat2_CatandBats_0" geometry={nodes.Bat2_CatandBats_0.geometry} material={materials.CatandBats} />
                </group>
                <group name="Bat3" position={[3.9, 3.26, 4.06]} rotation={[-1.59, -0.58, 3.05]} scale={3.86}>
                  <mesh name="Bat3_CatandBats_0" geometry={nodes.Bat3_CatandBats_0.geometry} material={materials.CatandBats} />
                </group>
                <group name="Chimney_" position={[2.9, 3.43, -0.34]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.1, 0.2, 0.2]}>
                  <mesh name="Chimney__House_0" geometry={nodes.Chimney__House_0.geometry} material={materials.House} />
                </group>
                <group name="ChimneySmokes" position={[2.93, 4.7, -0.45]} rotation={[-Math.PI / 2, 0, 0]} scale={0.68}>
                  <mesh name="ChimneySmokes_House_0" geometry={nodes.ChimneySmokes_House_0.geometry} material={materials.House} />
                </group>
                <group name="FrontDoor" position={[-0.32, 0.08, 1.33]} rotation={[-Math.PI / 2, 0, -1.99]} scale={[1, 0.54, 1]}>
                  <mesh name="FrontDoor_DoorsandBoards_0" geometry={nodes.FrontDoor_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="Gate" position={[0.27, -1.39, 6.71]} rotation={[-1.86, -0.01, 0.81]}>
                  <mesh name="Gate_DoorsandBoards_0" geometry={nodes.Gate_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="GatePosts" position={[0.66, -1.44, 6.71]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="GatePosts_DoorsandBoards_0" geometry={nodes.GatePosts_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="GraveMarkers" position={[-5.11, 0.21, -0.25]} rotation={[1.46, 0.17, 2.68]} scale={[-0.13, -0.06, -0.74]}>
                  <mesh name="GraveMarkers_DoorsandBoards_0" geometry={nodes.GraveMarkers_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="House" position={[-0.32, 0.08, 1.33]} rotation={[-Math.PI / 2, 0, -3.14]}>
                  <mesh name="House_House_0" geometry={nodes.House_House_0.geometry} material={materials.House} />
                </group>
                <group name="Kitty" position={[0.01, -1.08, 6.96]} rotation={[-Math.PI / 2, 0, -1.42]} scale={0.17}>
                  <mesh name="Kitty_CatandBats_0" geometry={nodes.Kitty_CatandBats_0.geometry} material={materials.CatandBats} />
                </group>
                <group name="LargeTree" position={[5.54, 4.92, -4.26]} rotation={[-1.65, 0.72, 2.21]}>
                  <mesh name="LargeTree_TreesandMoon_0" geometry={nodes.LargeTree_TreesandMoon_0.geometry} material={materials.TreesandMoon} />
                </group>
                <group name="LargeTreeLeft" position={[-4.65, -0.1, -4.91]} rotation={[-1.59, -0.27, 0.08]}>
                  <mesh name="LargeTreeLeft_TreesandMoon_0" geometry={nodes.LargeTreeLeft_TreesandMoon_0.geometry} material={materials.TreesandMoon} />
                </group>
                <group name="MediumTreeLeft" position={[-5.42, -1.13, 4.48]} rotation={[-1.61, -0.08, -3.09]}>
                  <mesh name="MediumTreeLeft_TreesandMoon_0" geometry={nodes.MediumTreeLeft_TreesandMoon_0.geometry} material={materials.TreesandMoon} />
                </group>
                <group name="MediumTreeRight" position={[5.18, -2.16, 4.39]} rotation={[-Math.PI / 2, 0, 0]} scale={1.68}>
                  <mesh name="MediumTreeRight_TreesandMoon_0" geometry={nodes.MediumTreeRight_TreesandMoon_0.geometry} material={materials.TreesandMoon} />
                </group>
                <group name="Moon" position={[8.83, 7.89, -16.05]} rotation={[3.12, 0.35, -2.27]}>
                  <mesh name="Moon_Moon_0" geometry={nodes.Moon_Moon_0.geometry} material={materials.Moon} />
                </group>
                <group name="Roof_Detail_Point1" position={[-2, 4.66, 1.79]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Roof_Detail_Point1_House_0" geometry={nodes.Roof_Detail_Point1_House_0.geometry} material={materials.House} />
                </group>
                <group name="RoofDetailPoint2" position={[2.24, 4.86, 0.68]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="RoofDetailPoint2_House_0" geometry={nodes.RoofDetailPoint2_House_0.geometry} material={materials.House} />
                </group>
                <group name="SmallTreeDoor" position={[1.38, -0.39, 2.82]} rotation={[-1.61, 0.22, 2.99]} scale={1.69}>
                  <mesh name="SmallTreeDoor_TreesandMoon_0" geometry={nodes.SmallTreeDoor_TreesandMoon_0.geometry} material={materials.TreesandMoon} />
                </group>
                <group name="SmallTreeFront" position={[-0.96, -1.71, 6.61]} rotation={[-1.57, 0.06, -0.5]}>
                  <mesh name="SmallTreeFront_TreesandMoon_0" geometry={nodes.SmallTreeFront_TreesandMoon_0.geometry} material={materials.TreesandMoon} />
                </group>
                <group name="Sphere" position={[-0.7, 0.17, 1.57]} rotation={[-Math.PI / 2, 0, -1.45]}>
                  <mesh name="Sphere_Pumpkins_0" geometry={nodes.Sphere_Pumpkins_0.geometry} material={materials.Pumpkins} />
                </group>
                <group name="Sphere001" position={[0.52, 0.02, 1.81]} rotation={[-Math.PI / 2, 0, -1.6]}>
                  <mesh name="Sphere001_Pumpkins_0" geometry={nodes.Sphere001_Pumpkins_0.geometry} material={materials.Pumpkins} />
                </group>
                <group name="Sphere002" position={[0.82, 0.05, 1.7]} rotation={[-1.24, -0.04, -1.39]}>
                  <mesh name="Sphere002_Pumpkins_0" geometry={nodes.Sphere002_Pumpkins_0.geometry} material={materials.Pumpkins} />
                </group>
                <group name="Sphere003" position={[0.54, 0.09, 1.6]} rotation={[-1.3, -0.2, -1.89]}>
                  <mesh name="Sphere003_Pumpkins_0" geometry={nodes.Sphere003_Pumpkins_0.geometry} material={materials.Pumpkins} />
                </group>
                <group name="WightHand" position={[3.6, 0.31, -3.68]} rotation={[0.78, -0.63, 1.25]} scale={1.2}>
                  <mesh name="WightHand_ZombieHand_0" geometry={nodes.WightHand_ZombieHand_0.geometry} material={materials.ZombieHand} />
                </group>
                <group name="WindowBoards" position={[-0.02, 4.4, -2.04]} rotation={[-1.63, -0.26, 0.22]}>
                  <mesh name="WindowBoards_DoorsandBoards_0" geometry={nodes.WindowBoards_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="Windows" position={[-0.32, 0.08, 1.33]} rotation={[-Math.PI / 2, 0, -3.14]}>
                  <mesh name="Windows_GlowingWindows_0" geometry={nodes.Windows_GlowingWindows_0.geometry} material={materials.GlowingWindows} />
                </group>
                <group name="Windows001" position={[-0.32, 0.08, 1.33]} rotation={[-Math.PI / 2, 0, -3.14]}>
                  <mesh name="Windows001_DarkWindows_0" geometry={nodes.Windows001_DarkWindows_0.geometry} material={materials.DarkWindows} />
                </group>
                <group name="Windows002" position={[-0.32, 0.08, 1.33]} rotation={[-Math.PI / 2, 0, -3.14]}>
                  <mesh name="Windows002_DarkWindows_0" geometry={nodes.Windows002_DarkWindows_0.geometry} material={materials.DarkWindows} />
                </group>
                <group name="Windows003" position={[-0.32, 0.08, 1.33]} rotation={[-Math.PI / 2, 0, -3.14]}>
                  <mesh name="Windows003_GlowingWindows_0" geometry={nodes.Windows003_GlowingWindows_0.geometry} material={materials.GlowingWindows} />
                </group>
                <group name="Windows005" position={[-0.32, 0.08, 1.33]} rotation={[-Math.PI / 2, 0, -3.14]}>
                  <mesh name="Windows005_DarkWindows_0" geometry={nodes.Windows005_DarkWindows_0.geometry} material={materials.DarkWindows} />
                </group>
                <group name="Windows006" position={[-0.32, 0.08, 1.33]} rotation={[-Math.PI / 2, 0, -3.14]}>
                  <mesh name="Windows006_DarkWindows_0" geometry={nodes.Windows006_DarkWindows_0.geometry} material={materials.DarkWindows} />
                </group>
                <group name="Bat3001" position={[-4.96, 4.09, -5]} rotation={[1.3, 0.48, -3.02]} scale={3.86}>
                  <mesh name="Bat3001_CatandBats_0" geometry={nodes.Bat3001_CatandBats_0.geometry} material={materials.CatandBats} />
                </group>
                <group name="WightHand001" position={[-0.16, 0.62, 0.97]} rotation={[-2.82, 0.79, -0.91]} scale={0.68}>
                  <mesh name="WightHand001_ZombieHand_0" geometry={nodes.WightHand001_ZombieHand_0.geometry} material={materials.ZombieHand} />
                </group>
                <group name="Cube001" position={[-2.37, -0.93, 4.59]} rotation={[-0.02, -0.25, 0.12]} scale={1.9}>
                  <mesh name="Cube001_Gravestones_0" geometry={nodes.Cube001_Gravestones_0.geometry} material={materials.Gravestones} />
                </group>
                <group name="Cube002" position={[-1.66, -0.14, 4.16]} rotation={[-0.02, -0.21, 0.05]} scale={2.05}>
                  <mesh name="Cube002_Gravestones_0" geometry={nodes.Cube002_Gravestones_0.geometry} material={materials.Gravestones} />
                </group>
                <group name="Cube003" position={[1.92, -0.37, 2.94]} rotation={[0.2, 0.28, -0.24]}>
                  <mesh name="Cube003_Gravestones_0" geometry={nodes.Cube003_Gravestones_0.geometry} material={materials.Gravestones} />
                </group>
                <group name="RedHatGnome" position={[-4.9, -0.5, 0.27]} rotation={[-1.12, -0.21, -0.31]}>
                  <mesh name="RedHatGnome_GnomeColor_0" geometry={nodes.RedHatGnome_GnomeColor_0.geometry} material={materials.GnomeColor} />
                </group>
                <group name="Sphere004" position={[-2.25, -1.07, 4.75]} rotation={[-1.61, -0.34, -1.66]}>
                  <mesh name="Sphere004_Pumpkins_0" geometry={nodes.Sphere004_Pumpkins_0.geometry} material={materials.Pumpkins} />
                </group>
                <group name="Sphere007" position={[-2.07, -0.93, 4.8]} rotation={[-1.27, -0.4, -1.88]}>
                  <mesh name="Sphere007_Pumpkins_0" geometry={nodes.Sphere007_Pumpkins_0.geometry} material={materials.Pumpkins} />
                </group>
                <group name="Sphere006" position={[-0.19, -1.6, 6.98]} rotation={[-1.56, 0.15, -2.59]}>
                  <mesh name="Sphere006_Pumpkins_0" geometry={nodes.Sphere006_Pumpkins_0.geometry} material={materials.Pumpkins} />
                </group>
                <group name="Sphere009" position={[1.63, -1.77, 6.78]} rotation={[-Math.PI / 2, 0, 1.57]}>
                  <mesh name="Sphere009_Pumpkins_0" geometry={nodes.Sphere009_Pumpkins_0.geometry} material={materials.Pumpkins} />
                </group>
                <group name="Sphere010" position={[1.35, -1.66, 6.85]} rotation={[-1.3, -0.2, -1.89]}>
                  <mesh name="Sphere010_Pumpkins_0" geometry={nodes.Sphere010_Pumpkins_0.geometry} material={materials.Pumpkins} />
                </group>
                <group name="Sphere011" position={[2.28, -0.59, 2.87]} rotation={[-1.58, 0.39, -1.51]}>
                  <mesh name="Sphere011_Pumpkins_0" geometry={nodes.Sphere011_Pumpkins_0.geometry} material={materials.Pumpkins} />
                </group>
                <group name="Sphere013" position={[5.41, -0.15, -3.04]} rotation={[-1.24, -0.04, -1.39]}>
                  <mesh name="Sphere013_Pumpkins_0" geometry={nodes.Sphere013_Pumpkins_0.geometry} material={materials.Pumpkins} />
                </group>
                <group name="Sphere015" position={[-4.89, 0.45, -3.75]} rotation={[-1.3, -0.2, -1.89]}>
                  <mesh name="Sphere015_Pumpkins_0" geometry={nodes.Sphere015_Pumpkins_0.geometry} material={materials.Pumpkins} />
                </group>
                <group name="WindowBoards001" position={[0.05, 4.05, -2.05]} rotation={[-1.42, 0.13, 0.07]}>
                  <mesh name="WindowBoards001_DoorsandBoards_0" geometry={nodes.WindowBoards001_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards002" position={[1.92, 2.51, -1.85]} rotation={[-1.83, 0.19, 0.1]}>
                  <mesh name="WindowBoards002_DoorsandBoards_0" geometry={nodes.WindowBoards002_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards003" position={[1.84, 2.19, -1.73]} rotation={[-1.93, -0.09, 0.11]}>
                  <mesh name="WindowBoards003_DoorsandBoards_0" geometry={nodes.WindowBoards003_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards004" position={[2.14, 2.64, 0.83]} rotation={[-1.79, -0.62, -0.1]}>
                  <mesh name="WindowBoards004_DoorsandBoards_0" geometry={nodes.WindowBoards004_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards005" position={[2.12, 2.33, 0.85]} rotation={[-1.62, 0.43, -0.02]}>
                  <mesh name="WindowBoards005_DoorsandBoards_0" geometry={nodes.WindowBoards005_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards006" position={[2.99, 0.67, -0.36]} rotation={[-1.4, 0.15, -1.34]}>
                  <mesh name="WindowBoards006_DoorsandBoards_0" geometry={nodes.WindowBoards006_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards007" position={[3.06, 0.36, -0.37]} rotation={[-1.99, -0.09, -1.37]}>
                  <mesh name="WindowBoards007_DoorsandBoards_0" geometry={nodes.WindowBoards007_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards008" position={[0.03, 2.67, 1.47]} rotation={[-1.47, 0.14, 0.23]}>
                  <mesh name="WindowBoards008_DoorsandBoards_0" geometry={nodes.WindowBoards008_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards009" position={[0.05, 2.4, 1.51]} rotation={[-1.47, -0.07, 0.25]}>
                  <mesh name="WindowBoards009_DoorsandBoards_0" geometry={nodes.WindowBoards009_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards012" position={[-2.05, 0.61, 2.6]} rotation={[1.65, -0.83, -2.99]}>
                  <mesh name="WindowBoards012_DoorsandBoards_0" geometry={nodes.WindowBoards012_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards013" position={[-2.01, 0.58, 2.53]} rotation={[-1.61, -1.25, 0.09]}>
                  <mesh name="WindowBoards013_DoorsandBoards_0" geometry={nodes.WindowBoards013_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards016" position={[-1.3, 0.66, 2.32]} rotation={[-1.57, -0.17, -2.25]} scale={0.58}>
                  <mesh name="WindowBoards016_DoorsandBoards_0" geometry={nodes.WindowBoards016_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards017" position={[-1.28, 0.42, 2.31]} rotation={[-1.69, -0.01, -2.24]} scale={0.58}>
                  <mesh name="WindowBoards017_DoorsandBoards_0" geometry={nodes.WindowBoards017_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards018" position={[-0.03, 0.7, -1.86]} rotation={[-1.63, -0.26, 0.22]}>
                  <mesh name="WindowBoards018_DoorsandBoards_0" geometry={nodes.WindowBoards018_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards019" position={[0.04, 0.35, -1.87]} rotation={[-1.42, 0.13, 0.07]}>
                  <mesh name="WindowBoards019_DoorsandBoards_0" geometry={nodes.WindowBoards019_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="FrontWeb" position={[1.73, 0.72, 1.07]} rotation={[2.66, -0.15, 2.33]}>
                  <mesh name="FrontWeb_Webs_0" geometry={nodes.FrontWeb_Webs_0.geometry} material={materials.Webs} />
                </group>
                <group name="FrontWeb001" position={[-1.69, 1.81, 1.93]} rotation={[2.65, -0.3, -3.03]}>
                  <mesh name="FrontWeb001_Webs_0" geometry={nodes.FrontWeb001_Webs_0.geometry} material={materials.Webs} />
                </group>
                <group name="FrontWeb002" position={[-0.99, 3.96, 0.81]} rotation={[2.64, 0.38, -2.68]}>
                  <mesh name="FrontWeb002_Webs_0" geometry={nodes.FrontWeb002_Webs_0.geometry} material={materials.Webs} />
                </group>
                <group name="FrontWeb003" position={[1.39, 4.06, -1.31]} rotation={[0.46, 0.01, 0.26]}>
                  <mesh name="FrontWeb003_Webs_0" geometry={nodes.FrontWeb003_Webs_0.geometry} material={materials.Webs} />
                </group>
                <group name="FrontWeb004" position={[1.56, 0.58, -1.92]} rotation={[0.76, 0.39, -0.22]}>
                  <mesh name="FrontWeb004_Webs_0" geometry={nodes.FrontWeb004_Webs_0.geometry} material={materials.Webs} />
                </group>
                <group name="WindowBoards020" position={[-1.88, 2.73, 1.86]} rotation={[-1.56, -0.52, 0.16]}>
                  <mesh name="WindowBoards020_DoorsandBoards_0" geometry={nodes.WindowBoards020_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="WindowBoards021" position={[-1.91, 2.42, 1.9]} rotation={[-1.53, 0.16, 0.24]}>
                  <mesh name="WindowBoards021_DoorsandBoards_0" geometry={nodes.WindowBoards021_DoorsandBoards_0.geometry} material={materials.DoorsandBoards} />
                </group>
                <group name="FenceIron" position={[2, -1.56, 6.48]} rotation={[-1.79, -0.07, -3.06]} scale={[1.25, 1, 1]}>
                  <mesh name="FenceIron_Fence_0" geometry={nodes.FenceIron_Fence_0.geometry} material={materials.Fence} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
